---
version: 2

project_name: osminokal

before:
  hooks:
    - "go mod tidy"

builds:
  - id: "osminokal"
    binary: "osminokal"
    main: "./main.go"
    env:
      - CGO_ENABLED=0
    ldflags:
      - "-s -w"
      - "-X github.com/Appel-flappen/osminokal/version.Version={{.Version}}"
      - "-X github.com/Appel-flappen/osminokal/version.Commit={{.Commit}}"
      - "-X github.com/Appel-flappen/osminokal/version.BuildDate={{.Date}}"

    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - id: "targz"
    formats:
      - "tar.gz"
    # should be osminokal_1.0.0_Linux_x86_64.tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    files:
      - LICENCE
      - README.md

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: "appel-flappen"
    name: "osminokal"
  name_template: "Release {{ .Tag }}"
  draft: true
  prerelease: auto
  skip_upload: true

dockers_v2:
  - id: "osminokal-image"
    dockerfile: ./Containerfile
    ids:
      - "osminokal"
    platforms:
      - linux/amd64
      - linux/arm64
    images:
      - "ghcr.io/appel-flappen/osminokal"
    tags:
      - "latest"
      - "v{{ .Version }}"
    labels:
      "org.opencontainers.image.description": "Add Octopus Energy free electricity sessions to your calendar."
      "org.opencontainers.image.created": "{{.Date}}"
      "org.opencontainers.image.name": "{{.ProjectName}}"
      "org.opencontainers.image.revision": "{{.FullCommit}}"
      "org.opencontainers.image.version": "{{.Version}}"
      "org.opencontainers.image.source": "{{.GitURL}}"
